name: CI

on: [push]

jobs:
 sast_scan:
   name: Exécution du scan avec Bandit
   runs-on: ubuntu-latest

   steps:
   - name: Vérification de code
     uses: actions/checkout@v2

   - name: Configurer python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8

   - name: Installation de Bandit
     run: pip install bandit
     
   - name: Exécuter le scan avec Bandit
     run: bandit -ll -ii -r . -f json -o rapport-bandit.json
   
   - name: Charger l'artéfact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: recherche-bandit
       path: rapport-bandit.json

 scan_image:
   name: Build l'image et Exécution du scan de l'image
   runs-on: ubuntu-latest

   steps:
   - name: Vérification de code
     uses: actions/checkout@v4
     
   - name: Installation de Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10'

   - name: Construire l'image Docker
     run: docker build -f Dockerfile -t myapp:latest .

   - name: Scan avec Docker Scout
     run: |
       curl -fsSL https://github.com/docker/scout-cli/blob/main/install.sh -o install-scout.sh
       sh install-scout.sh
       docker scout quickview
       docker scout cves

  
